# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.5.0"

pre_release = true

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.6/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]
    [notes.util-linux-tools]
        title = "Util Linux Tools"
        description = """\
Util Linux Tools is now shipped as a system extension. Includes fstrim only.
"""

    [notes.intel-ice-firmware]
        title = "Intel ICE firmware"
        description = """\
Intel ice firmware (E810) is now shipped as a system extension.
"""

    [notes.amdgpu-firmware]
        title = "AMD GPU firmware"
        description = """\
AMD GPU firmware is now shipped as a system extension.
"""

    [notes.btrfs]
        title = "BTRFS"
        description = """\
BTRFS drivers is now supported as Talos System Extension.
"""

    [notes.binfmt_misc]
        title = "binfmt_misc"
        description = """\
`binfmt_misc` Linux module extension is now supported as Talos System Extension.
"""

    [notes.zfs]
        title = "ZFS"
        description = """\
ZFS extensions now also ship zfs-tools and an extension service that imports all zpools on startup.
"""

    [notes.stargz]
        title = "stargz-snapshotter"
        description = """\
stargz-snapshotter extension is now supported as Talos System Extension.
"""

    [notes.updates]
        title = "Component Updates"
        description = """\
* DRBD: 9.2.5
* QEMU agent: v8.1.1
* Tailscale: 1.50.0
* Xen Guest Utilities: 8.3.1
* Linux Firmware: 20230919
* gasket driver: 09385d4
"""


[make_deps]
